name: Sync Repository with GCS

# Execute this on changes to repository/repository/
on:
  # When a new root is published.
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'repository/repository/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-20.04
    permissions:
      id-token: 'write'
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: 1.17.x
      - uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # v0.5.1
        with:
          project_id: project-rekor
          install_components: alpha
      # Setup OIDC->SA auth
      - uses: google-github-actions/auth@81012c2689e66f7f020ed6d8ab43596a0f8b503a # v0.6.0
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/237800849078/locations/global/workloadIdentityPools/root-signing-pool/providers/sigstore-root'
          service_account: 'sigstore-root-signing@project-rekor.iam.gserviceaccount.com'
          create_credentials_file: true
      - name: Login
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth list
      # Sync
      # TODO(asraa): Use a stable API or switch to gsutil cp when gsutil supports  workload identity federation
      - name: sync
        run: |
          gcloud alpha --quiet storage cp -r repository/repository/* gs://sigstore-tuf-root/
