name: CI Validate

on:
  push:
    branches: [ main ]
    paths:
      - 'ceremony/**'
      - 'repository/**'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
        with:
          fetch-depth: 2
      - run: |
          echo "REPO=$(pwd)/repository" >> $GITHUB_ENV
          echo "GCS_REPO=https://storage.googleapis.com/sigstore-tuf-root" >> $GITHUB_ENV
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.16.4'
      - name: install deps
        run: |
          sudo apt-get install libpcsclite-dev
          curl -fsO https://developers.yubico.com/PIV/Introduction/piv-attestation-ca.pem
      - name: build verification
        run: go build -o verify ./cmd/verify/
      - name: build TUF script
        run: go build -o tuf -tags=pivkey ./cmd/tuf
      - name: verify local published repository
        run: |
          set -euo pipefail
          if [ -d "$REPO" ]; then
            ./verify repository --repository $REPO --root $(pwd)/repository/repository/root.json
          fi
      - name: verify GCS remote published repository
        run: ./verify repository --repository $GCS_REPO --root $(pwd)/ceremony/2021-06-18/repository/root.json
      - name: verify staged ceremony changes
        run: |
          set -euo pipefail
          export CHANGED=$(git diff --name-only HEAD^ HEAD ceremony/ | grep ".*staged.*" | head -1)
          echo "$CHANGED"
          if [ -n "$CHANGED" ]; then
            export REPO=$(echo "$CHANGED" | cut -d/ -f 1-2)
            ./verify repository --repository "$REPO" --staged true
          fi

